Repository amitbhudiya/CITS5206_DialogCoder, pull requests merged in 2025-04, with the labels that each got.

#29 TC-PROC-002: Refactor `file_processor.py` and add comprehensive unit tests
  .gitignore
  data/batch/test.csv
  data/batch/test2.csv
  data/output.csv
  data/test2.csv
  src/file_processor.py
  src/test_file_processor.py
Labels: enhancement

#31 Created a page based Streamlit app
  app/Home.py
  app/main.py
  app/pages/Dictionary.py
  app/pages/Reports.py
  app/pages/Upload.py
  app/styles.css
  app/uploaded_dictionaries/dictionary.csv
Labels: enhancement, Development

#34 TC-UI-006: Implement custom sidebar navigation to replace default page order
  app/.streamlit/config.toml
  app/Home.py
  app/pages/Dictionary.py
  app/pages/Reports.py
  app/pages/Upload.py
Labels: bug, enhancement

#36 TC-REP-001: Add dynamic report generation based on uploaded dictionary
  app/pages/Reports.py
  app/pages/Upload.py
Labels: Development

#38 Feature/tc dict 002 changing file structure in dictionary
  app/pages/Dictionary.py
Labels: enhancement, Development

#40 Navigation Bar Unification and Frequency Summary Fix
  app/Home.py
  app/components/sidebar.py
  app/pages/Dictionary.py
  app/pages/Reports.py
  app/pages/Upload.py
  uploaded_reports/processed_test.csv
  uploaded_reports/summary_frequency.csv
Labels: bug, enhancement, Development

#43 TC-REP-001: Fix front-end logic to classify using B5T instead of code column
  app/pages/Reports.py
  app/pages/Upload.py
  app/uploaded_dictionaries/dictionary.csv
  requirements.txt
  src/file_processor.py
  uploaded_reports/processed_test.csv
  uploaded_reports/summary_frequency.csv
Labels: bug, enhancement, Development

#46 [TC-UI-008] Persist upload previews via session_state
  app/pages/Upload.py
Labels: Development
