Repository amitbhudiya/CITS5206_DialogCoder, pull requests merged in 2025-05, with the labels that each got.

#51 Fixed footnote issue
  app/components/footer.py
Labels: bug, Development

#64 created test folder and added e2e selenium headless tests
  tests/__init__.py
  tests/conftest.py
  tests/e2e/__init__.py
  tests/e2e/test_homepage_smoke.py
  tests/sample_files/dictionary.csv
  tests/unit/__init__.py
Labels: Testing

#75 Update README.md
  README.md
Labels: documentation

#74 TC-OPS-001 · TC-NLP-001 · TC-PROC-001 · TC-UI-001: Plan B Online LLM MVP
  .github/workflows/ci.yml
  .github/workflows/planb-ci.yml
  README.md
  planb/__init__.py
  planb/column_inference/infer_columns.py
  planb/controller/dispatcher.py
  planb/logging/logger.py
  planb/persistence/exporter.py
  planb/pipeline/aggregator.py
  planb/pipeline/explanation.py
  planb/pipeline/keyword_matcher.py
  planb/pipeline/llm_adapter.py
  planb/requirements-planb.txt
  planb/ui/app.py
  tests/planb/__init__.py
  tests/planb/test_aggregator.py
  tests/planb/test_column_inference.py
  tests/planb/test_exporter.py
  tests/planb/test_keyword_matcher.py
Labels: Development, PLAN B, LLM

#77 chore: apply code style fixes (autoflake, isort, black)
  .github/workflows/ci.yml
  app/Home.py
  app/__init__.py
  app/components/footer.py
  app/components/sidebar.py
  app/pages/Dictionary.py
  app/pages/Reports.py
  app/pages/Upload.py
  app/settings.py
  planb/__init__.py
  planb/column_inference/infer_columns.py
  planb/controller/dispatcher.py
  planb/logging/logger.py
  planb/persistence/exporter.py
  planb/pipeline/aggregator.py
  planb/pipeline/explanation.py
  planb/pipeline/keyword_matcher.py
  planb/pipeline/llm_adapter.py
  planb/ui/app.py
  src/classifier.py
  src/file_processor.py
  src/summary_report.py
  src/test_file_processor.py
  tests/__init__.py
  tests/conftest.py
  tests/e2e/__init__.py
  tests/e2e/test_homepage_smoke.py
  tests/planb/__init__.py
  tests/planb/test_aggregator.py
  tests/planb/test_column_inference.py
  tests/planb/test_exporter.py
  tests/planb/test_keyword_matcher.py
  tests/unit/test_dictionary_upload.py
Labels: bug

#80 Fix issues with dictionary upload and upload page
  app/pages/Dictionary.py
  app/pages/Upload.py
  app/uploaded_dictionaries/dictionary.csv
  src/file_processor.py
  tests/e2e/test_homepage_smoke.py
Labels: bug, Development

#82 Refactor: update `.gitignore`, fix `REPORT_FOLDER` path and unit test for Upload module, update requirements
  .gitignore
  Project Files/Client Communication Records/Client Communication_1.pdf
  Project Files/Client Communication Records/Client Communication_2.pdf
  Project Files/Client Communication Records/Client Communication_3.pdf
  Project Files/Meeting Minutes/Meeting Agenda & Meeting Minutes.docx
  app/pages/Upload.py
  planb/pipeline/llm_adapter.py
  planb/requirements-planb.txt
  tests/sample_files/batch/test_1.csv
  tests/sample_files/batch/test_2.csv
  tests/sample_files/test.csv
  tests/unit/test_file_processor.py
Labels: bug, documentation, enhancement, Testing

#89 Bugfix: Streamlit print error while no dictionary
  app/pages/Upload.py
  src/classifier.py
  src/file_processor.py
Labels: bug
